---
title: "FinalProject"
author: "Pablo Suarez, Deep Goon, William Schwartz, Matthew Stuart, Maximilian Howarth"
date: "4/8/2020"
Outcome: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#### Import all libraries
```{r}
## Load all the libraries
library(stringr)
library(lattice)
library(ggplot2)
library(caret)
library(class)
library(neuralnet)
library(kernlab)
library(C50)
library(randomForest)
```



## Loading and Exploring Data
```{r}
diabetes <- read.csv("diabetes.csv")
str(diabetes)
table(diabetes$Outcome)
```

## Data Cleaning, Randomization and Normalization
```{r}
# Randomize data
set.seed(42)
rows <- sample(nrow(diabetes))
diabetes <- diabetes[rows, ]

# Build Model Matrix to deal with all the factors (if any)
diabetes <- as.data.frame(model.matrix(~ . -1, data = diabetes))

# Remove NAs or impute missing values
diabetes$Pregnancies <- ifelse(is.na(diabetes$Pregnancies),mean(diabetes$Pregnancies,na.rm = TRUE),diabetes$Pregnancies)
diabetes$Glucose <- ifelse(is.na(diabetes$Glucose),mean(diabetes$Glucose,na.rm = TRUE),diabetes$Glucose)
diabetes$BloodPressure <- ifelse(is.na(diabetes$BloodPressure),mean(diabetes$BloodPressure,na.rm = TRUE),diabetes$BloodPressure)
diabetes$SkinThickness <- ifelse(is.na(diabetes$SkinThickness),mean(diabetes$SkinThickness,na.rm = TRUE),diabetes$SkinThickness)
diabetes$Insulin <- ifelse(is.na(diabetes$Insulin),mean(diabetes$Insulin,na.rm = TRUE),diabetes$Insulin)
diabetes$BMI <- ifelse(is.na(diabetes$BMI),mean(diabetes$BMI,na.rm = TRUE),diabetes$BMI)
diabetes$DiabetesPedigreeFunction <- ifelse(is.na(diabetes$DiabetesPedigreeFunction),mean(diabetes$DiabetesPedigreeFunction,na.rm = TRUE),diabetes$DiabetesPedigreeFunction)
diabetes$Age <- ifelse(is.na(diabetes$Age),mean(diabetes$Age,na.rm = TRUE),diabetes$Age)

# Normalize data
normalize <- function(x) { 
  return((x - min(x)) / (max(x) - min(x)))
}

diabetes_norm <- as.data.frame(lapply(diabetes, normalize))

# Build train and test data
diabetes_train <- diabetes_norm[1:600, ]
diabetes_train_labels <- diabetes_norm[1:600, 9]
diabetes_test <- diabetes_norm[601:768, ]
diabetes_test_labels <- diabetes_norm[601:768, 9]

```

## Models

### Logistic Model
```{r}
# Logistic Models

# First model
log1<- glm(Outcome ~., family="binomial", data=diabetes_train)
summary(log1)

# Second Model, AIC score reduced but marginally
log2<- glm(Outcome ~ Pregnancies + Glucose + BloodPressure + BMI + DiabetesPedigreeFunction  , family="binomial", data=diabetes)
summary(log2)
plot(log2)

#nrow(diabetes_test)
## Predict using the best model
for(row in 1:nrow(diabetes_test)){
  predictor <- predict(log1, newdata = diabetes_test[row,],  type = "response")
  predictor <- ifelse(is.na(predictor), 0, predictor)
  
  diabetes_test[row, "is_diabetic"] <- ifelse( predictor >= 0.005, 1, 0)
}

diabetes_test$is_diabetic
confusionMatrix(as.factor(diabetes_test$is_diabetic), as.factor(diabetes_test_labels))
levels(as.factor(diabetes_test$is_diabetic))

## Store predictions in a different variable and make test data usable again
log_predictions <- diabetes_test$is_diabetic
diabetes_test$is_diabetic <- NULL
```


### KNN Model
```{r}
# Build first model
diabetes_test_pred_1 <- knn(train = diabetes_train, test = diabetes_test,
                      cl = diabetes_train_labels, k=27)
confusionMatrix(table(diabetes_test_pred_1, diabetes_test_labels))

length(diabetes_train_labels)

# Build second model with optimized K: BEST MODEL
diabetes_test_pred_2 <- knn(train = diabetes_train, test = diabetes_test,
                      cl = diabetes_train_labels, k=26)

confusionMatrix(table(diabetes_test_pred_2, diabetes_test_labels))


# Try Z score optimization
diabetes_z <- as.data.frame(scale(diabetes_norm))
diabetes_train_z <- diabetes_z[1:600, ]
diabetes_test_z <- diabetes_z[601:768, ]

diabetes_test_pred_3 <- knn(train = diabetes_train_z, test = diabetes_test_z,
                      cl = diabetes_train_labels, k=27)
confusionMatrix(table(diabetes_test_pred_3, diabetes_test_labels))
knn_pred <- diabetes_test_pred_2
```
### ANN model  || Current highest accuracy achieved: 74.46%
```{r}
#Model 1
# simple ANN ith only a single hidden neuron
diabetes_model_1 <- neuralnet(formula = Outcome ~ ., data = diabetes_train)
plot(diabetes_model_1, rep = "best")

model_result_1 =  compute(diabetes_model_1, diabetes_test)
predicted_strength_1 = model_result_1$net.result


binary_ps_1 = ifelse(predicted_strength_1>0.6,1,0) #change this value

# Build the confusion matrix
a_1  <- as.factor(diabetes_test$Outcome)
b_1 <- as.factor(binary_ps_1)


confusionMatrix( b_1, a_1)


# Model 3
# simple ANN with only a 2 hidden neurons
diabetes_model_3 <- neuralnet(formula = Outcome ~ ., data = diabetes_train, hidden=10)
plot(diabetes_model_3, rep = "best")

model_result_3 =  compute(diabetes_model_3, diabetes_test)
predicted_strength_3 = model_result_3$net.result
binary_ps_3 = ifelse(predicted_strength_3>0.6,1,0) #change this value

# Build the confusion matrix
a_3  <- as.factor(diabetes_test$Outcome)
b_3  <- as.factor(binary_ps_3)

confusionMatrix(b_3, a_3)

```
## Build the SVM Model
```{r}
#diabetes_train$Outcome <- as.factor(diabetes_train$Outcome)
#diabetes_test$Outcome <- as.factor(diabetes_test$Outcome)


model_svm_1 <- ksvm(as.factor(Outcome) ~ ., data = diabetes_train, kernel = "vanilladot")

diabetes_predict_1 <- predict(model_svm_1, diabetes_test)

confusionMatrix(as.factor(diabetes_predict_1), as.factor(diabetes_test_labels))

model_svm_2 <- ksvm(as.factor(Outcome)  ~ ., data = diabetes_train, kernel = "rbfdot")

diabetes_predict_2 <- predict(model_svm_2, diabetes_test)

confusionMatrix(as.factor(diabetes_predict_2), as.factor(diabetes_test_labels))
```
## Build a C5 Model 
```{r}
diabetes_train_labels <- as.factor(diabetes_train_labels)
#diabetes_rf_model <- C5.0(diabetes_train, diabetes_train_labels)

# Model 1
diabetes_rf_model <- C5.0(as.factor(Outcome) ~ ., data=diabetes_train)
diabetes_c_pred <- predict(diabetes_rf_model, diabetes_test)
confusionMatrix(table(diabetes_c_pred, diabetes_test_labels))

# Model 2, Improve by increasing number of trials
diabetes_rf_model <- C5.0(as.factor(Outcome) ~ ., data=diabetes_train, trials=10)
diabetes_c_pred <- predict(diabetes_rf_model, diabetes_test)
confusionMatrix(table(diabetes_c_pred, diabetes_test_labels))

# Model 3, Improve by creating a cost matrix
error_cost <- matrix(c(0, 1, 4, 0), nrow = 2)
diabetes_rf_model <- C5.0(as.factor(Outcome) ~ ., data=diabetes_train, trials=10, costs = error_cost)
diabetes_c_pred <- predict(diabetes_rf_model, diabetes_test)
confusionMatrix(table(diabetes_c_pred, diabetes_test_labels))


plot(diabetes_rf_model)
```
# Random Forests


```{r}
set.seed(300)
rf <- randomForest(as.factor(Outcome) ~ ., data = diabetes_train)

tree_random_forest_prediction <- predict(rf, diabetes_test)

plot(rf)

confusionMatrix(table(tree_random_forest_prediction, diabetes_test_labels))
```
